[package]
authors = ["ishiko <ishiko732@gmail.com>"]
edition = "2024"
name = "fsrs-binding"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.2.0", default-features = true }
napi-derive = "3.2.0"
csv = "1.3.0"
time = { version = "0.3", default-features = false, features = [
  "alloc",
  # "macros",
] }
serde = "1.0.228"
serde_json = "1.0.143"

[dependencies.fsrs]
git = "https://github.com/open-spaced-repetition/fsrs-rs"
# https://github.com/open-spaced-repetition/fsrs-rs/pull/370
rev = "0187b45608ec9470b74f289aaaf0069b458220df"
default-features = false

[build-dependencies]
napi-build = "2"
