[package]
authors = ["ishiko <ishiko732@gmail.com>"]
edition = "2024"
name = "fsrs-binding"
version = "0.0.2"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.4.0", default-features = true }
napi-derive = "3.3.0"
csv = "1.3.0"
time = { version = "0.3", default-features = false, features = [
  "alloc",
  # "macros",
] }
serde = "1.0.228"
serde_json = "1.0.143"
itertools = "0.14.0"

[dependencies.fsrs]
git = "https://github.com/open-spaced-repetition/fsrs-rs"
# https://github.com/open-spaced-repetition/fsrs-rs/pull/382
rev = "b46226aae5ea03959c27cd81abb603bb6b744907"
default-features = false

[build-dependencies]
napi-build = "2"
