[package]
authors = ["ishiko <ishiko732@gmail.com>"]
edition = "2024"
name = "fsrs-binding"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.0.0", default-features = true }
napi-derive = "3.0.0"
csv = "1.3.0"
time = { version = "0.3", default-features = false, features = [
  "alloc",
  # "macros",
] }
serde = "1.0.219"
serde_json = "1.0.143"

[dependencies.fsrs]
version = "5.2.0"
default-features = false

[build-dependencies]
napi-build = "2"
